# --- S3: bucket de alertas (alertas-caseiro) ---
ALERTS_AWS_ACCESS_KEY_ID = "AKIA3LZFPH2H22X2JMPK"
ALERTS_AWS_SECRET_ACCESS_KEY = "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"
ALERTS_AWS_REGION = "us-east-1"
ALERTS_BUCKET = "alertas-caseiro"
ALERTS_PREFIX = "alerts/"

# --- S3: bucket de triggers (aviario-metrics) ---
TRIGGERS_AWS_ACCESS_KEY_ID = "AKIA3LZFPH2H22X2JMPK"
TRIGGERS_AWS_SECRET_ACCESS_KEY = "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"
TRIGGERS_AWS_REGION = "us-east-1"
TRIGGERS_BUCKET = "aviario-metrics"
TRIGGERS_PREFIX = "triggers/"

# --- Amazon SES (envio de emails) ---
SES_REGION = "us-east-1"
SES_SENDER = "Caseiro Alerts <pedro.h.li.edu@gmail.com>"
SES_RECIPIENTS = "maintenance@company.com, it@company.com"
